jobs:
  check-x86-linux:
    name: Check x86_64-linux configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [installer-iso, nixosConfigurations.installed]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Build ${{ matrix.config }} configuration
        run:
          nix build .#${{ matrix.config
          }}.config.system.build.toplevel --dry-run
  auto-merge:
    needs: [check-x86-linux]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
